---

- name: Make sure the required folders are present
  file:
    state: directory
    path: "{{ item }}"
    recurse: yes
  with_items:
    - "/etc/fonts"
    - "{{ dstBase }}/.config/gconf/apps"
    - "{{ dstBase }}/.config/nvim"
    - "{{ dstBase }}/.i3"
    - "{{ dstBase }}/.ssh"
    - "{{ dstBase }}/.vim"
    - "{{ dstBase }}/.vim/bundle"
    - "{{ dstBase }}/.tmux/plugins"

- name: Create Symlinks for public files
  file:
    src: "{{ srcBase }}/.dotfiles/{{ item.src }}"
    dest: "{{ dstBase }}/{{ item.dst }}"
    state: link
    force: yes
  with_items:
    - { src: "aliases", dst: ".aliases" }
    - { src: "antibody_bundle", dst: ".antibody_bundle" }
    - { src: "autorandr", dst: ".config/autorandr" }
    - { src: "bash_profile", dst: ".bash_profile" }
    - { src: "bashrc", dst: ".bashrc" }
    - { src: "bindings", dst: ".bindings" }
    - { src: "dockerfunc", dst: ".dockerfunc" }
    - { src: "dunst", dst: ".config/dunst" }
    - { src: "exports", dst: ".exports" }
    - { src: "fzf", dst: ".fzf" }
    - { src: "fzf.zsh", dst: ".fzf.zsh" }
    - { src: "gdbinit", dst: ".gdbinit" }
    - { src: "gitignore", dst: ".gitignore" }
    - { src: "gitconfig", dst: ".gitconfig" }
    - { src: "guake", dst: ".config/gconf/apps/guake" }
    - { src: "i3/config", dst: ".config/i3" }
    - { src: "i3/config", dst: ".i3/config" }
    - { src: "i3/polybar", dst: ".i3/polybar" }
    - { src: "i3/scripts", dst: ".i3/scripts" }
    - { src: "inputrc", dst: ".inputrc" }
    - { src: "nanorc", dst: ".nanorc" }
    - { src: "nanorc-folder", dst: ".nano" }
    - { src: "nvim/init.vim", dst: ".config/nvim/init.vim" }
    - { src: "powerline-config", dst: ".config/powerline" }
    - { src: "powerline/powerline/bindings/tmux/powerline.conf", dst: ".powerline.conf" }
    - { src: "ranger", dst: ".config/ranger" }
    - { src: "radare2rc", dst: ".radare2rc" }
    - { src: "termite", dst: ".config/termite" }
    - { src: "tpm", dst: ".tmux/plugins/tpm" }
    - { src: "tmux.conf", dst: ".tmux.conf" }
    - { src: "vim/colors", dst: ".vim/colors" }
    - { src: "vim/snippets", dst: ".vim/snippets" }
    - { src: "vim-vundle", dst: ".vim/bundle/Vundle.vim" }
    - { src: "vimrc", dst: ".vimrc" }
    - { src: "xmodmap", dst: ".Xmodmap" }
    - { src: "xinitrc", dst: ".xinitrc" }
    - { src: "xresources", dst: ".Xresources" }
    - { src: "zshrc", dst: ".zshrc" }

- include_tasks: "{{ srcBase }}/.dotfiles/{{ secrets_config }}/tasks.yml"
  when: secrets_config is defined

- include_tasks: "{{ srcBase }}/.dotfiles/shared-secrets/tasks.yml"
  when: shared_repo_url is defined
