---

- name: Install arch dependencies via pacman
  package: name={{ item }} state=latest
  with_items:
    - chromium
    - i3lock
    - perl
    - powerline
    - light
    - powerline-common
    - python-powerline
    - python2-powerline
    - playerctl
    - the_silver_searcher
    - termite
    - termite-terminfo
    - xorg-xbacklight
    - xorg-xev
    - xorg-xprop
    - xorg-xrandr
    - xorg-xdpyinfo

- name: Install trizen (with test for CI)
  shell: |
    pacman -S --noconfirm trizen || su yaourt -c "yaourt -S --noconfirm trizen"

- name: Get PGP key for cower
  shell: |
    gpg --recv-keys --keyserver hkp://keyserver.ubuntu.com 1EB2638FF56C0C53
  become: no

- name: Install arch dependencies via trizen
  shell: |
    source /etc/profile && \
    trizen -S --noconfirm --needed \
      cower \
      network-manager-applet \
      polybar \
      ttf-hack \
      pulseaudio-bluetooth-a2dp-gdm-fix \
      fix-bt-a2dp \
      pulseaudio-modules-bt-git \
      libldac \
      antibody \
      alttab-git
  become: no
