---

- name: Install general dependencies via package manager
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - arandr
    - blueman
    - cmake
    - dunst
    - feh
    - git
    - gimp
    - gparted
    - i3-wm
    - lxappearance
    - nautilus
    - pass
    - ranger
    - rofi
    - scrot
    - w3m
    - wicd-gtk
    - xclip
    - xdotool
    - xss-lock
    - zsh

- name: Installing python (Arch)
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python2
    - python2-pip
    - python
    - python-pip
  when: ansible_distribution == "Archlinux"

- name: Installing python (Debian/Ubuntu)
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python2.7
    - python-pip
    - python3
    - python3-pip
  when: ansible_distribution != "Archlinux"

- name: Update pip packages
  shell: |
    pip2 install -U pip && pip3 install -U pip

- name: Install pip2 dependencies
  shell: |
    pip2 install i3ipc

- name: Install pip3 dependencies
  shell: |
    pip3 install pipenv i3ipc yapf pylint

- name: Install autorandr
  shell: |
      git clone https://github.com/phillipberndt/autorandr.git /opt/autorandr &&
      cd /opt/autorandr &&
      make install && (pidof /sbin/init | :) &&
      command -v systemctl && systemctl daemon-reload &&
      command -v systemctl && systemctl enable autorandr.service &&
      command -v udevadm && udevadm control --reload-rules
  args:
    executable: /bin/bash

- include_tasks: arch.yml
  when: ansible_distribution == "Archlinux"

- include_tasks: debian.yml
  when: "ansible_distribution == 'Debian' or 'Kali' in ansible_distribution"

- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
