---

- name: Install ubuntu dependencies via apt-get
  package: name={{ item }} state=latest
  with_items:
    - apt-transport-https
    - chromium-browser
    - chromium-browser-l10n
    - chromium-codecs-ffmpeg
    - cmake
    - fonts-hack-ttf
    - gvfs-bin
    - gcc
    - i3
    - libssl-dev
    - network-manager-gnome
    - python-pygments
    - silversearcher-ag
    - software-properties-common
    - update-notifier
    - w3m-img
    - x11-utils
    - x11-xserver-utils
    - xbacklight
    - zsh-common

- name: Install polybar ubuntu dependencies via apt-get
  package: name={{ item }} state=latest
  with_items:
    - cmake
    - cmake-data
    - pkg-config
    - libcairo2-dev
    - libxcb1-dev
    - libxcb-util0-dev
    - libxcb-randr0-dev
    - python-xcbgen
    - xcb-proto
    - libxcb-image0-dev
    - libxcb-ewmh-dev
    - libxcb-icccm4-dev
    - libxcb-xkb-dev
    - libxcb-xrm-dev
    - libxcb-cursor-dev
    - libasound2-dev
    - libpulse-dev
    - i3-wm
    - libjsoncpp-dev
    - libmpdclient-dev
    - libcurl4-openssl-dev
    - libiw-dev
    - libnl-3-dev
    - libxcb-composite0-dev

- name: Install polybar
  shell: |
    if ! which polybar; then
    mkdir -p /tmp/polybar-temp && cd /tmp/polybar-temp && \
    git clone --recursive https://github.com/jaagr/polybar && \
    mkdir -p polybar/build && cd polybar/build && \
    cmake .. && make install && \
    rm -rf /tmp/polybar-temp
    fi

- name: Install termite
  shell: |
    if ! which termite; then
    mkdir -p /tmp/termite-temp && cd /tmp/termite-temp && \
    git clone --recursive https://github.com/thestinger/termite.git && \
    git clone https://github.com/thestinger/vte-ng.git && \
    sudo apt-get install -y \
      g++ \
      libgtk-3-dev \
      gtk-doc-tools \
      gnutls-bin \
      valac \
      intltool \
      libpcre2-dev \
      libglib3.0-cil-dev \
      libgnutls28-dev \
      libgirepository1.0-dev \
      libxml2-utils \
      libtool \
      gperf && \
    echo export LIBRARY_PATH="/usr/include/gtk-3.0:$LIBRARY_PATH" && \
    cd vte-ng && ./autogen.sh && make && make install && \
    cd ../termite && make && make install && \
    ldconfig && \
    mkdir -p /lib/terminfo/x && \
    ln -s /usr/local/share/terminfo/x/xterm-termite /lib/terminfo/x/xterm-termite && \
    rm -rf /tmp/termite-temp
    fi

- name: Install playerctl
  shell: |
    cd /tmp && \
    curl https://api.github.com/repos/acrisci/playerctl/releases/latest | \
      grep 'browser_download_url' | \
      grep 'amd64.deb' | \
      cut -d ':' -f 2,3 | \
      tr --delete '\"' | \
      tr --delete ' ' | \
      wget -O /tmp/playerctl.deb -i - && \
    dpkg -i /tmp/playerctl.deb && \
    rm /tmp/playerctl.deb
